import { expect, test } from '@playwright/test'
import type { Locator, Page } from '@playwright/test'

// 只通过真实 Tab 寻找入口,不调用 focus() 跳过键盘路径。
async function tabTo(page: Page, target: Locator): Promise<void> {
  for (const attempt of Array.from({ length: 12 }, (_, index) => index)) {
    if (await target.evaluate((element) => element === document.activeElement)) return
    await page.keyboard.press('Tab')
    if (attempt === 11) await expect(target).toBeFocused()
  }
}

test('语言 disclosure:真实键盘切换、内容同步与 Esc 还焦', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const header = page.locator('.site-header')
  const trigger = header.getByRole('button', { name: 'Language', exact: true })
  await expect(trigger).toBeVisible()
  await tabTo(page, trigger)
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Enter')
  const group = header.getByRole('group', { name: 'Language', exact: true })
  const chinese = group.getByRole('button', { name: '中文', exact: true })
  const english = group.getByRole('button', { name: /English/ })
  await expect(chinese).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(english).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page).toHaveTitle('Mia —— 你的 AI Agent,随时随地')
  await expect(page.getByRole('heading', { level: 1, name: '随时在你身边的 AI Agent' })).toBeVisible()
  const chineseTrigger = header.getByRole('button', { name: '语言', exact: true })
  await expect(chineseTrigger).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(header.getByRole('button', { name: /中文.*当前语言/ })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(chineseTrigger).toBeFocused()
  await expect(chineseTrigger).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page).toHaveTitle('Mia — your AI agent, wherever you are')
  await expect(page.getByRole('heading', { level: 1, name: 'Your AI agent, always within reach' })).toBeVisible()
  await expect(trigger).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('language-keyboard.png') })
})

test('账户 disclosure:键盘可达、Esc 关闭、登出二次确认与还焦', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const header = page.locator('.site-header')
  const login = header.getByRole('button', { name: 'Sign in', exact: true })
  await tabTo(page, login)
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/workspace$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Workspace', exact: true })).toBeVisible()
  const account = header.getByRole('button', { name: 'Account menu: 林一舟', exact: true })
  await tabTo(page, account)
  await expect(account).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(header.getByRole('link', { name: 'Workspace', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(account).toBeFocused()
  await expect(account).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  const signOut = header.getByRole('group', { name: 'Account menu', exact: true }).getByRole('button', { name: 'Sign out', exact: true })
  await expect(signOut).toBeFocused()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Sign out?', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('sign-out-confirm.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(signOut).toBeFocused()
  await expect(page).toHaveURL(/#\/workspace$/)
  await page.keyboard.press('Enter')
  await expect(dialog).toBeVisible()
  await page.mouse.click(1, 1)
  await expect(dialog).not.toBeVisible()
  await expect(signOut).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Sign out', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).not.toHaveURL(/#/)
  await expect(login).toBeVisible()
  await expect(login).toBeFocused()
  await expect(account).toHaveCount(0)
})

test('工作台守卫、返回首页、原生链接与刷新即重置', async ({ page }) => {
  await page.goto('/#/workspace?s=error')
  await expect(page).not.toHaveURL(/#/)
  const header = page.locator('.site-header')
  await expect(header.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await header.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/#\/workspace$/)
  await header.getByRole('link', { name: 'Mia', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Your AI agent, always within reach' })).toBeVisible()
  await expect(header.getByRole('button', { name: 'Sign in', exact: true })).toHaveCount(0)
  await header.getByRole('button', { name: 'Account menu: 林一舟', exact: true }).click()
  await header.getByRole('link', { name: 'Workspace', exact: true }).click()
  await expect(page).toHaveURL(/#\/workspace$/)
  await page.reload()
  await expect(page).not.toHaveURL(/#/)
  await expect(header.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
})

for (const width of [375, 768, 1280, 1600]) {
  test(`账户与工作台壳 @${width}:不溢出且无运行错误`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('console', (message) => {
      if (message.type() === 'error') errors.push(message.text())
    })
    page.on('response', (response) => {
      if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`)
    })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Workspace', exact: true })).toBeVisible()
    const account = page.getByRole('button', { name: 'Account menu: 林一舟', exact: true })
    await account.click()
    const group = page.getByRole('group', { name: 'Account menu', exact: true })
    await expect(group).toBeVisible()
    const dimensions = await account.boundingBox()
    expect(dimensions?.width).toBeGreaterThanOrEqual(44)
    expect(dimensions?.height).toBeGreaterThanOrEqual(44)
    const bounds = await group.boundingBox()
    expect(bounds?.x).toBeGreaterThanOrEqual(0)
    expect((bounds?.x ?? 0) + (bounds?.width ?? 0)).toBeLessThanOrEqual(width)
    expect(await page.locator('html').evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath(`workspace-account-${width}.png`) })
    expect(errors).toEqual([])
  })
}
